name: CI checks

on:
  - push

jobs:
  build:
    name: Build and test

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.12.1

    runs-on: ${{ matrix.os }}
    
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 80:8700

    env:
      HTTPBIN: http://localhost:8700

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: "Use NodeJS v16"
        uses: actions/setup-node@v3
        with:
         node-version: 16

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          opam-depext: false
          opam-pin: false

      - run: opam pin add skapm.1.6.0 -n https://github.com/skolemlabs/skapm.git#1.6.0
      - run: opam pin add skrest.dev -n .
      - run: opam pin add skrest_js.dev -n .
      - run: opam pin add skrest_unix.dev -n .
      - run: opam depext -yt skrest
      - run: opam install -t . --deps-only
      - run: opam exec -- dune build --profile=release
      - run: opam exec -- dune runtest
